### ISSUE TITLE
what is the file format of the .gosync file ?

### ISSUE THREAD

**Issue by archupsg03** [Redundancy/go-sync#6]

**Comment by Redundancy** [comment]
I'll document the current format, but note that the CLI tool is merely intended as a guide and acceptance testing instrument. There's no particular effort on my part to provide any form of stability or compatibility.

**Comment by Redundancy** [comment]
Should be covered by: fa14f35ac8f3aa41aa13991c5a0be4183a6d35ac 
https://github.com/Redundancy/go-sync/blob/master/gosync/fileformat.md
